### ISSUE TITLE
Broken deployments

### ISSUE THREAD

**Issue by sambryant4** [cloudfoundry/cf-mysql-deployment#4]
It is currently impossible to deploy this when using smoke-tests or brokers, the ops files have been migrated to use functionality of cf-mysql-release that was added in v36 but the release is hardcoded to v35.

**Comment by sambryant4** [comment]
I am guessing the `latest-release` ops file has been used for testing as this fixes the issues, but the base deployment is broken.

**Comment by sambryant4** [comment]
Using an ops file to fix this for ourselves right now.

```
---
- type: replace
  path: /releases/name=cf-mysql
  value:
    name: cf-mysql
    url: http://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=36
    version: 36
    sha1: 746240c005465ffa105ee89e53e401e311b4fbf8
```
